spring:
  application:
    name: his_security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: 060601hyz
  cloud:
    nacos:
      discovery:
        server-addr: 111.230.250.144:8848
server:
  port: 9002

his-system-management:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule


hm:
  jwt:
    location: classpath:hmall.jks # ????
    alias: hmall # ????
    password: hmall123 # ??????
    tokenTTL: 300m # ?????