spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: 060601hyz
  data:
    redis:
      host: localhost
      port: 6379
      password: 060601hyz
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
              - TRACE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: systemanagement
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/users/**,/roles/**,/permissions/**
        - id: bed
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/beds/**
        - id: patient
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/patient/**

server:
  port: 9090

hm:
  jwt:
    location: classpath:hmall.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 300m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /users/login
      - /users/register